// General
export const APP_LOAD = 'APP_LOAD'
export const REDIRECT = 'REDIRECT'
export const SET_PAGE = 'SET_PAGE'

// Auth
export const LOGIN = 'LOGIN'
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const REGISTER = 'REGISTER'
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const LOGOUT = 'LOGOUT'

// Profile
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED'
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED'
export const SETTINGS_SAVED = 'SETTINGS_SAVED'

// Editor
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED'
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR'
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED'
export const ARTICLE_SUBMITTED = 'ARTICLE_SUBMITTED'

// Article
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED'
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'

// Comment
export const ADD_COMMENT = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
