const CLOUD_NAME = 'unimemo-dfd94'
export const CLOUDINARY_UPLOAD_URL = 'https://api.cloudinary.com/v1_1/' + CLOUD_NAME + '/image/upload'
export const CLOUDINARY_API_KEY = '662315467465218'
export const CLOUDINARY_API_SECRET = 'iRAAwz3vCuSMMF8bs67-_pu4IlQ'
export const CLOUDINARY_UPLOAD_PRESET = 'unimemo-dfd94'
